### ISSUE TITLE
Test build all pull requests using travis?

### ISSUE THREAD

**Issue by petterreinholdtsen** [CasparCG/server#1144]
This is related to the discussions in #690 and #683, which proposed to set up Travis.

It would be great if every pull request was automatically built to verify the code is building on Linux.  As there are already docker rules in place, I suspect all that is needed is a simple .travis.yml file in the root of the git repository and some credentials.  A simple example can be found in https://github.com/johang/vlc-bittorrent/blob/master/.travis.yml, looking like this:

```
language: cpp
os: linux
services:
  - docker
compiler:
  - gcc
  - clang
env:
  - IMAGE=ubuntu:latest DOCKERFILE=debian
  - IMAGE=ubuntu:rolling DOCKERFILE=debian
  - IMAGE=ubuntu:devel DOCKERFILE=debian
  - IMAGE=debian:stable DOCKERFILE=debian CXXFLAGS="-std=c++11"
  - IMAGE=debian:testing DOCKERFILE=debian
  - IMAGE=debian:unstable DOCKERFILE=debian
  - IMAGE=opensuse/leap:latest DOCKERFILE=opensuse CXXFLAGS="-std=c++11"
  - IMAGE=opensuse/tumbleweed:latest DOCKERFILE=opensuse
before_install:
  - docker build --build-arg IMAGE=$IMAGE -t img -f test/dockerfiles/Dockerfile.$DOCKERFILE .
script:
  - docker run -e CC -e CXX -e CXXFLAGS img
```

It would make it trivial to test all new code using both clang (see #1141) and gcc, and on several Linux distributions.

A more elaborate example (using Python, so less like CasparCG), where code coverage is checked and any reduction in code coverage is reported as a failure, can be seen in https://github.com/translate/translate/blob/master/.travis.yml:

```
#True httpsTrue://travis-ci.org/#!/translate/translate
sudo: required  # For now these builds are faster
language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
env:
  matrix:
    - USECPO=0 MINVERSION= META=
    #- USECPO=2
matrix:
  include:
    # Obtain Python 3.7 from xenial as per https://github.com/travis-ci/travis-ci/issues/9815
    - python: 3.7
      dist: xenial
      sudo: true
    # Do additional variations with Python 2.7 only
    - python: 2.7
      env: USECPO=0 MINVERSION=1 META=
    - python: 2.7
      env: USECPO=0 MINVERSION= META=1
install:
  - pip install coveralls
  - pip install codecov
  - if [[ $MINVERSION ]]; then make requirements/min-versions.txt; cat requirements/min-versions.txt;  CFLAGS="-O0" pip install -r requirements/min-versions.txt; fi
  - if [[ ! $MINVERSION ]]; then  CFLAGS="-O0" pip install -r requirements/dev.txt; fi
  # Still need to handle with indexing engines
  - pip freeze
script:
  - if [[ ! $META ]]; then python -m compileall -q -f .; fi     # Compile all the files
  - if [[ ! $META ]]; then python setup.py --quiet build; fi
  - if [[ ! $META ]]; then pip install .; fi
  - if [[ ! $META ]]; then py.test --cov=. -r EfsxX -W error::DeprecationWarning ; fi
  - if [[ ! $META ]]; then make test-functional; fi
  - if [[ $META ]]; then pycodestyle; fi
  - if [[ $META ]]; then pydocstyle; fi
  - if [[ $META ]]; then make docs; fi
after_success:
  - coveralls
  - codecov
notifications:
  email:
    on_failure: always
    on_success: change
addons:
  apt:
    packages:
      - gettext
      - libgettextpo-dev
```
